persistent_notification:
  create:
    description: Show a notification in the frontend

    fields:
      message:
        description: Message body of the notification. [Templates accepted]
        example: Please check your configuration.yaml.

      title:
        description: Optional title for your notification. [Optional, Templates accepted]
        example: Test notification

      notification_id:
        description: Target ID of the notification, will replace a notification with the same Id. [Optional]
        example: 1234

homematic:
  virtualkey:
    description: Press a virtual key from CCU/Homegear or simulate keypress

    fields:
      address:
        description: Address of homematic device or BidCoS-RF for virtual remote
        example: BidCoS-RF

      channel:
        description: Channel for calling a keypress
        example: 1

      param:
        description: Event to send i.e. PRESS_LONG, PRESS_SHORT
        example: PRESS_LONG
